version: '3'
services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - themosis
  nginx:
    container_name: nginx-themosis
    image: nginx
    working_dir: /var/www/html/themosis
    volumes:
      - ./themosis.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/themosis
    expose:
      - "80"
    restart: always
    environment:
      - VIRTUAL_HOST=banahia.xyz
    depends_on:
      - php
      - mysql
    networks:
      - themosis

  php:
    container_name: php-themosis
    restart: always
    build:
      args:
        user: ubuntu
        uid: 1000
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html/themosis
    volumes:
      - ./:/var/www/html/themosis
    networks:
      - themosis

  mysql:
    image: mysql:5.7.33
    container_name: mysql
    ports:
      - "33068:3306"
    restart: always
    environment:
      MYSQL_DATABASE: themosis
      MYSQL_ROOT_PASSWORD: admin.root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - themosis

networks:
  themosis:
    driver: bridge
